### ISSUE TITLE
Getting started: include failing

### ISSUE THREAD

**Issue by BartmanEH** [Chunjee/biga.ahk#1]
I figured out how to install Node.js and, hence, npm (but without the tools for compiling) and have installed biga.ahk using npm. I have placed the following in my AHK file:
```
#Include %A_ScriptDir%\node_modules
#Include biga.ahk\export.ahk
```
But get the error:
![IMG_0131](https://user-images.githubusercontent.com/6135879/113366524-7328e680-9327-11eb-9f3b-f16cdde49922.jpeg)

So something is messed up with my paths, I assume. I was hoping that having used npm to install biga.ahk that I wouldn’t have such issues.

I see that npm installs into the current folder. This is very inconvenient compared to other package managers like homebrew. So I need to clutter up my AHK project folder with an npm install of biga.ahk?

**Comment by Chunjee** [comment]
I don't think this has anything to do with the library itself. Therefore there is nothing to fix. Reminder you only need to include export.ahk so `#Include %A_ScriptDir%\node_modules\biga.ahk\export.ahk` might be easier to understand or troubleshoot.

> npm installs into the current folder

Only by default. I prefer it that way so each project can update as warranted or stay on an old version if needed.
 `-g` global flag installs to some other windows location. 
 
 npm may not be the perfect perfect package manager for ahk or your project style. But it's the best I've found so far.
